# Generated by Django 5.2.4 on 2025-08-03 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateField(verbose_name='تاریخ ورود'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.DateField(verbose_name='تاریخ خروج'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت رزرو'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام رزرو کننده'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.room', verbose_name='اتاق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.PositiveSmallIntegerField(verbose_name='تعداد تخت'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(upload_to='rooms/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام اتاق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('luxury', 'لوکس'), ('economic', 'اقتصادی'), ('suite', 'سوییت خانوادگی')], max_length=20, verbose_name='نوع اتاق'),
        ),
    ]
