# Generated by Django 5.2.4 on 2025-08-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_booking_checkin_alter_booking_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.FloatField(verbose_name='تعداد تخت'),
        ),
    ]
