# Generated by Django 5.2.4 on 2025-08-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_room_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد اعتبار پرداخت (Authority)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت پرداخت'),
        ),
    ]
